# Generated by Django 4.2.16 on 2024-11-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='users',
            new_name='user',
        ),
    ]
